server:
  port: 8080

spring:
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.67.132:3307/ubuntu_test?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: docker_mysql8
  data:
    redis:
      host: 192.168.67.132
      port: 6380

#  thymeleaf:
    #自定义的Thymeleaf的模板位置，jar内部以classpath:开头，外部路径使用file:开头
   # prefix: file:J:/qrCode/index/
  #  suffix: .html
  #  cache: false
   # mode: HTML
  #  encoding: UTF-8
  #  servlet:
   #   content-type: text/html
  mail:
    host: smtp.qq.com
    username: 532221723@qq.com
    password: qtdscjrvzmlacahg

    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        starttls:
          enable: true
          required: true
    default-encoding: utf-8
    port: 465





mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml



